### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by strayedstar** [BPI-SINOVOIP/BPI-R4-OPENWRT-V21.02#2]
system:ubuntu focal/archlinux
gcc/g++ version:gcc-8 g++/gcc-9.3 g++9.3/gcc-12 g++12/gcc-13 g++13
binutils version:2.34/2.42

make error:
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/kernel/crypto-eip/Makefile' has a dependency on 'strongswan', which does not exist
WARNING: Makefile 'package/kernel/crypto-eip/Makefile' has a dependency on 'strongswan-default', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
make[1]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[2]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[2]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
rm -rf /home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek
make[2]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[3]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux'
make[4]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/mediatek'
rm -f /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/localversion
/home/ls/BPI-R4-OPENWRT-V21.02-main/scripts/kconfig.pl  + /home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/generic/config-5.4 /home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/mediatek/mt7988/config-5.4 > /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/ls/BPI-R4-OPENWRT-V21.02-main/.config >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target
/home/ls/BPI-R4-OPENWRT-V21.02-main/scripts/package-metadata.pl kconfig /home/ls/BPI-R4-OPENWRT-V21.02-main/tmp/.packageinfo /home/ls/BPI-R4-OPENWRT-V21.02-main/.config 5.4 > /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.override
/home/ls/BPI-R4-OPENWRT-V21.02-main/scripts/kconfig.pl 'm+' '+' /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.target /dev/null /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.override > /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set
mv /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.old
grep -v INITRAMFS /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.old > /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set
rm -rf /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/modules
cmp -s /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.prev || { cp /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config; cp /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.prev; }
export MAKEFLAGS= ; [ -d /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/user_headers ] || make -C /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246 KCFLAGS="-fmacro-prefix-map=/home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Feb  1 11:38:38 2024" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.246 CC="aarch64-openwrt-linux-musl-gcc" INSTALL_HDR_PATH=/home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/user_headers headers_install
grep '=[ym]' /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.config.set | LC_ALL=C sort | mkhash md5 > /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.vermagic
touch /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.configured
rm -f /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/vmlinux /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/System.map
make -C /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246 KCFLAGS="-fmacro-prefix-map=/home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Feb  1 11:38:38 2024" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.246 CC="aarch64-openwrt-linux-musl-gcc" modules
make[5]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246'
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  Building modules, stage 2.
  MODPOST 170 modules
make[5]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246'
touch /home/ls/BPI-R4-OPENWRT-V21.02-main/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7988/linux-5.4.246/.modules
make -C image compile TARGET_BUILD=
make[5]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/mediatek'
make[5]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[5]: Nothing to be done for 'compile'.
make[5]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/mediatek/image'
make[4]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux/mediatek'
make[3]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/target/linux'
time: target/linux/compile#3.07#3.83#3.96
make[2]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
export MAKEFLAGS= ;make -w -r buildinfo
make[2]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[2]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
 make[3] diffconfig buildversion feedsversion
make[2]: *** No rule to make target 'package/cryptsetup/host/compile', needed by 'package/compile'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/package/libs/libjson-c'
mkdir -p /home/ls/BPI-R4-OPENWRT-V21.02-main/dl
SHELL= flock /home/ls/BPI-R4-OPENWRT-V21.02-main/tmp/.json-c-0.15-nodoc.tar.gz.flock -c '       /home/ls/BPI-R4-OPENWRT-V21.02-main/scripts/download.pl "/home/ls/BPI-R4-OPENWRT-V21.02-main/dl" "json-c-0.15-nodoc.tar.gz" "99bca4f944b8ced8ae0bbc6310d6a3528ca715e69541793a1ef51f8c5b4b0878" "" "https://s3.amazonaws.com/json-c_releases/releases/"    '
make[3]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main/package/libs/libjson-c'
time: package/libs/libjson-c/host-compile#0.07#0.11#0.16
make[2]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[1]: *** [package/Makefile:116: /home/ls/BPI-R4-OPENWRT-V21.02-main/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make[1]: Leaving directory '/home/ls/BPI-R4-OPENWRT-V21.02-main'
make: *** [/home/ls/BPI-R4-OPENWRT-V21.02-main/include/toplevel.mk:230: world] Error 2

Always fail when making josn-c,opkg and vendor SDcard bootimage is broken,so how I can make a vendor image?

**Comment by Frkchs** [comment]
I have the same exact problem! Compilation always fails.

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
Binutils: 2.38
Ubuntu 22.04.4 LTS jammy

**Comment by strayedstar** [comment]
> I have the same exact problem! Compilation always fails.
> 
> gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) Binutils: 2.38 Ubuntu 22.04.4 LTS jammy

create some dictionary and file to enable crypto-eip，{package/cryptsetup/host/compile，package/dtc/host/compile}。and then I struck in cypto-eip make process。
may I need switch my gcc version?
